version: '3.9' 

 

services: 

  web: 

    build: ./backend 

    volumes: 

      - ./backend:/app 

    ports: 

      - "8000:8000" 

    depends_on: 

      - mongo 

 

  mongo: 

    image: mongo:6.0 

    ports: 

      - "27017:27017" 

    volumes: 

      - mongo_data:/data/db 

 

volumes: 

  mongo_data: 